# ==============================================================
# validate_rev2.py - REV2 validation harness
# --------------------------------------------------------------
# Validates the current REV2 submission generated by cube_6m_Rev2.py.
#
# Engineering validation logic is identical to validate_rev3.py;
# only the REV2 file/output references were adapted.
#
# Usage:
#   python validate_rev2.py
#
# Prerequisite: run both generators once (headless is fine):
#   cube_6m_Rev1_baseline.py   -> cube_nodes_6m_Rev1_generated.xlsx
#   cube_6m_Rev2.py            -> cube_nodes_6m_Rev2_generated.xlsx
# ==============================================================

from pathlib import Path

import numpy as np
import pandas as pd

folder = Path(__file__).resolve().parent

rev2_py = folder / "cube_6m_Rev2.py"
rev1_xlsx = folder / "cube_nodes_6m_Rev1_generated.xlsx"
rev2_xlsx = folder / "cube_nodes_6m_Rev2_generated.xlsx"
rev1_png = folder / "cube_6m_Rev1_generated.png"
rev2_png = folder / "cube_6m_Rev2_generated.png"

failures = []
passed = 0


def check(name, ok, detail=""):
    global passed
    status = "PASS" if ok else "FAIL"
    print(f"[{status}] {name}" + (f"  ({detail})" if detail else ""))
    if ok:
        passed += 1
    else:
        failures.append(name)


def df_equals(left, right, tol=1.0e-9):
    if list(left.columns) != list(right.columns):
        return False
    if len(left) != len(right):
        return False
    if len(left) == 0:
        return True
    try:
        return bool(np.allclose(left.to_numpy(dtype=float),
                                right.to_numpy(dtype=float),
                                rtol=0.0, atol=tol))
    except (TypeError, ValueError):
        return left.equals(right)


# --------------------------------------------------------------
# 1. Output artifacts exist
# --------------------------------------------------------------
check("REV1 workbook exists", rev1_xlsx.exists())
check("REV2 Python file exists", rev2_py.exists())
check("REV2 Python file labeled Rev. 2 (not Rev. 3)",
      rev2_py.exists() and "REV. 2" in rev2_py.read_text(encoding="utf-8")
      and "REV. 3" not in rev2_py.read_text(encoding="utf-8"))
check("REV2 workbook exists", rev2_xlsx.exists())
check("REV1 PNG exists (REV1 preserved)", rev1_png.exists())
check("REV2 PNG exists", rev2_png.exists())

# --------------------------------------------------------------
# 2. Read both workbooks
# --------------------------------------------------------------
rev1 = {s: pd.read_excel(rev1_xlsx, sheet_name=s)
        for s in ["Information", "Nodes", "Node DOF", "Member Incidences",
                  "Member DOF", "Supports", "End Releases", "Local Axes"]}

rev2_sheet_names = pd.ExcelFile(rev2_xlsx).sheet_names
check("REV2 workbook has all 8 REV1 sheets",
      all(s in rev2_sheet_names for s in rev1.keys()))
check("REV2 sheet: Nodes = 8",
      len(pd.read_excel(rev2_xlsx, sheet_name="Nodes")) == 8)
check("REV2 sheet: Members = 12",
      len(pd.read_excel(rev2_xlsx, sheet_name="Member Incidences")) == 12)
check("REV2 sheet: 48 DOFs (Node DOF max = 48)",
      len(pd.read_excel(rev2_xlsx, sheet_name="Node DOF")) == 8
      and int(pd.read_excel(rev2_xlsx, sheet_name="Node DOF")
              .to_numpy(dtype=float).max().round()) == 48)

rev2 = {s: pd.read_excel(rev2_xlsx, sheet_name=s)
        for s in rev2_sheet_names}

# --------------------------------------------------------------
# 3. Regression - REV1 core content preserved
# --------------------------------------------------------------
for sheet in ["Nodes", "Node DOF", "Member DOF", "Supports",
              "End Releases", "Local Axes"]:
    check(f"REV1 == REV2 sheet: {sheet}",
          df_equals(rev1[sheet], rev2[sheet]))

# Member Incidences: REV1 columns must match exactly.
rev1_inc = list(rev1["Member Incidences"].columns)
check("Member Incidences (REV1 cols) preserved",
      df_equals(rev1["Member Incidences"],
                rev2["Member Incidences"][rev1_inc]))

# Information: every REV1 item (except the Revision tag) unchanged.
info_rev1 = rev1["Information"].dropna()
info_rev2 = rev2["Information"].set_index("Item")["Value"].to_dict()
ok = True
for _, row in info_rev1.iterrows():
    item, value = row["Item"], row["Value"]
    if item == "Revision":
        continue
    if item not in info_rev2 or info_rev2[item] != value:
        ok = False
check("Information sheet (REV1 items) preserved", ok)

# --------------------------------------------------------------
# 4. REV2 database-driven additions
# --------------------------------------------------------------
check("REV2 sheet: Member Sections",
      "Member Sections" in rev2_sheet_names)
check("REV2 sheet: Materials", "Materials" in rev2_sheet_names)
check("REV2 sheet: Unit Systems", "Unit Systems" in rev2_sheet_names)
check("REV2 sheet: Conversion Factors",
      "Conversion Factors" in rev2_sheet_names)
check("REV2 sheet: Section Detail - W6X9",
      "Section Detail - W6X9" in rev2_sheet_names)

ms = rev2["Member Sections"]
check("Member Sections row count = 12", len(ms) == 12)
check("All members carry material A36 Gr.36",
      set(ms["Material Label"]) == {"A36 Gr.36"})
check("All members carry section W6X9",
      set(ms["Section Label"]) == {"W6X9"})
check("All member lengths = 6.0 m",
      np.allclose(ms["Length (m)"], 6.0))
check("Area A = 1729 mm^2",
      np.allclose(ms["Area (mm2)"], 1729.0, atol=1.5))

mat = rev2["Materials"]
a36 = mat[mat["Label"].astype(str).str.strip() == "A36 Gr.36"]
check("Materials sheet contains A36 Gr.36", len(a36) == 1)
check("A36 E = 199,948 MPa (DB-driven)",
      np.isclose(float(a36.iloc[0]["E [MPa]"]), 199948.0, atol=10.0))
check("A36 Fy = 248.2 MPa (DB-driven)",
      np.isclose(float(a36.iloc[0]["Yield / f'c / f'm [MPa]"]), 248.2,
                 atol=0.2))

info_v2 = rev2["Information"].set_index("Item")["Value"].to_dict()
check("Information has Unit system = Standard Metric",
      info_v2.get("Unit system") == "Standard Metric")
check("Information references W6X9",
      "W6X9" in str(info_v2.get("Section")))
check("Revision tag = Rev. 2", info_v2.get("Revision") == "Rev. 2")

us = rev2["Unit Systems"]
check("Unit Systems sheet populated",
      len(us) > 0 and "Moment of inertia" in
      us["Quantity"].astype(str).values)
cf = rev2["Conversion Factors"]
check("Conversion Factors sheet populated",
      len(cf) > 0 and "Moment of inertia" in
      cf["Quantity"].astype(str).values)

detail = rev2["Section Detail - W6X9"]
check("Section Detail references W6X9",
      any("W6X9" in str(value)
          for value in detail.values.ravel() if value is not None))

# --------------------------------------------------------------
# 4B. Solver / stability checks (from the Engine Diagnostics sheet)
# --------------------------------------------------------------
edf = rev2["Engine Diagnostics"]
ed_by_check = edf.set_index("Check")


def ed_val(name):
    return ed_by_check.loc[name, "Value"]


def ed_pass(name):
    return bool(ed_by_check.loc[name, "Pass"])


check("K_global dimensions = 48 x 48", ed_val("K_global dimensions") == "48 x 48")
check("K_global symmetry (max|K-KT| <= 1e-9)",
      ed_pass("K_global symmetry |K-KT| max"))
check("Restrained DOFs = 12", format(ed_val("Restrained DOFs")) == "12")
check("Free DOFs = 36", format(ed_val("Free DOFs")) == "36")
check("rank(K_ff) = 34 (confirmed REV1 model)",
      format(ed_val("rank(K_ff)")) == "34")
check("rank(K_ff) expected value recorded as 36",
      format(ed_by_check.loc["rank(K_ff)", "Expected"]) == "36")
check("deficiency (free - rank) = 2",
      format(ed_val("deficiency (free - rank)")) == "2")
check("member stiffness ranks (beams=4, columns=6)",
      ed_pass("member k_eff ranks (M1..M12)"))
check("axial sanity K[UX1,UX2] = -EA/L",
      ed_pass("axial sanity K[UX1,UX2] (kN/m)"))
check("Structural solution BLOCKED",
      "BLOCKED" in str(ed_val("Structural solution status")))
check("Solver blocking correctness (no solve on singular K_ff)",
      ed_pass("Solver blocking correctness"))
check("No fabricated displacements",
      str(ed_val("Displacements fabricated")) == "NO")
check("No fabricated reactions", str(ed_val("Reactions fabricated")) == "NO")
check("No fabricated member-end forces",
      str(ed_val("Member-end forces fabricated")) == "NO")
check("Load case is TEST-A (TEST ONLY, not professor-specified)",
      str(ed_val("Load case")) == "TEST-A")

disp = rev2["Node Displacements"]
check("Displacements sheet has NO computed values (blocked)",
      all(pd.isna(disp[col]).all()
          for col in ["UX (m)", "UY (m)", "UZ (m)",
                      "RX (rad)", "RY (rad)", "RZ (rad)", "|u| (m)"]))
rxn = rev2["Support Reactions"]
check("Reactions sheet has NO computed values (blocked)",
      pd.isna(rxn["Reaction (kN)"]).all())
mef = rev2["Member End Forces"]
check("Member End Forces sheet has NO computed values (blocked)",
      pd.isna(mef[["N (kN)", "Vy (kN)", "Vz (kN)",
                   "T (kN-m)", "My (kN-m)", "Mz (kN-m)"]]).all().all())
ld = rev2["Loads"]
check("Loads sheet documents TEST-A",
      any("TEST-A" in str(v) for v in ld.values.ravel() if v is not None))

check("Information: Solver status shows BLOCKED",
      "BLOCKED" in str(info_v2.get("Solver status")))
check("Information: Stability status shows UNSTABLE",
      "UNSTABLE" in str(info_v2.get("Stability status")))

# REV1 baseline FILE must remain untouched (Rev.1 content, no solver).
bl_path = folder / "cube_6m_Rev1_baseline.py"
bl_text = bl_path.read_text(encoding="utf-8") if bl_path.exists() else ""
check("REV1 baseline file unchanged (Rev.1, no solver engine)",
      bl_path.exists() and "REV. 1" in bl_text and
      "11B. SOLVER ENGINE" not in bl_text)

# --------------------------------------------------------------
# 5. Summary
# --------------------------------------------------------------
print()
if failures:
    print(f"VALIDATION FAILED: {len(failures)} of {passed + len(failures)} "
          f"checks failed:")
    for name in failures:
        print(f"  - {name}")
    raise SystemExit(1)
print(f"VALIDATION PASSED: all {passed} checks passed.")